version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a5:01:84:1c:7b:99:d7:0d:10:13:55:d0:d8:dd:ef:f1"
      - checkout
      - run:
          name: Set NODE_NO_WARNINGS variable
          command: export NODE_NO_WARNINGS=1
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: 
          name: Build Docker image
          command: docker build -t nicolaszelarayan/reciclargnode:$CIRCLE_SHA1 .
      - run: 
          name: Push Docker image
          command: docker push nicolaszelarayan/reciclargnode:$CIRCLE_SHA1
      - run:
          name: Clean up unused Docker images
          command: docker system prune -f
      - run: 
          name: Pull the latest code
          command: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "cd /home/nicolas_zelarayan/node/reciclarg-node && sudo git pull"
      - run:
          name: Stop and remove any existing container
          command: |
            ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker stop reciclarg_node || true"
            ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker rm reciclarg_node || true"
      - run:
          name: Run Docker Compose
          command: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "cd /home/nicolas_zelarayan/node/reciclarg-node && sudo IMAGE_TAG=$CIRCLE_SHA1 docker-compose up -d"
