version: 2
jobs:
  build:
    machine: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "25:43:dd:b2:55:3d:b1:c7:f1:8b:85:fd:1c:f5:19:47"
      - checkout
      - run:
          name: Set NODE_NO_WARNINGS variable
          command: export NODE_NO_WARNINGS=1
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t nicolaszelarayan/reciclargnode:$CIRCLE_SHA1 .
      - run: docker push nicolaszelarayan/reciclargnode:$CIRCLE_SHA1
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "cd /home/nicolas_zelarayan/node/reciclarg-node && sudo git pull"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "cd /home/nicolas_zelarayan/node/reciclarg-node && sudo docker build -t nicolaszelarayan/reciclargnode:$CIRCLE_SHA1 -f Dockerfile ."
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker stop reciclarg_node || true"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker rm reciclarg_node || true"
      - run: ssh -o StrictHostKeyChecking=no -t -t nicolas_zelarayan@reciclarg.cloud "sudo docker run -p 3000:3000 -d --name reciclarg_container nicolaszelarayan/reciclargNode:$CIRCLE_SHA1"
